"use client";

import { BadgeCheck, Building2, FilePenLine, ShieldCheck, TrendingUp } from "lucide-react";
import type { Locale } from "@/lib/types";
import Link from "next/link";

export type PartnerApplicationRow = {id:string;name:string;contact:string;type:string;status:string;submittedAt:string|null};
export type ListingReviewRow = {id:string;name:string;destination:string;createdAt:string;status:string};

export function AdminDashboard({locale,applications,requestCount,villaCount,reviewQueue}:{locale:Locale;applications:PartnerApplicationRow[];requestCount:number;villaCount:number;reviewQueue:ListingReviewRow[]}){
  const rows=applications;const reviews=reviewQueue;
  return <div className="dashboard-shell"><div className="container"><div className="dash-head"><div><div className="eyebrow muted">FindVillas staff</div><h1 className="serif">{locale==="th"?"ศูนย์ควบคุม":"Operations overview"}</h1></div><button className="btn btn-dark"><ShieldCheck size={17}/> Staff tools</button></div>
    <div className="stat-grid"><div className="stat-card"><div className="stat-label">Booking requests</div><div className="stat-value">{requestCount}</div><span className="status live"><TrendingUp size={11}/> local data</span></div><div className="stat-card"><div className="stat-label">Partner approvals</div><div className="stat-value">{rows.filter(row=>row.status==="approved").length}</div></div><div className="stat-card"><div className="stat-label">Published villas</div><div className="stat-value">{villaCount}</div></div><div className="stat-card"><div className="stat-label">Need review</div><div className="stat-value">{rows.filter(row=>["submitted","under_review"].includes(row.status)).length+reviews.filter(row=>["submitted","under_review"].includes(row.status)).length}</div></div></div>
    <div className="dash-grid"><div className="panel"><div className="panel-head"><h2>Partner applications</h2><span className="status pending">{rows.filter(row=>["submitted","under_review"].includes(row.status)).length} need review</span></div><div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Contact</th><th>Submitted</th><th>Status</th><th>Review</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><br/><span className="muted">{row.id}</span></td><td>{row.contact}<br/><span className="muted">{row.type.replaceAll("_"," ")}</span></td><td>{row.submittedAt?new Date(row.submittedAt).toLocaleDateString():"Draft"}</td><td><span className={`status ${row.status==="approved"?"live":row.status==="rejected"?"declined":"pending"}`}>{row.status.replaceAll("_"," ")}</span></td><td><Link className="mini-btn approve" href={`/${locale}/admin/partner-applications/${row.id}`}>Review application</Link></td></tr>):<tr><td colSpan={5} className="muted">No partner applications yet.</td></tr>}</tbody></table></div></div>
      <div className="panel"><div className="panel-head"><h2>Property compliance</h2><FilePenLine size={17}/></div><div className="activity-list">{reviews.length?reviews.map(item=><div className="activity" key={item.id}><span className="activity-icon"><Building2 size={16}/></span><div style={{width:"100%"}}><p><strong>{item.name}</strong><br/>{item.destination} · <span className="status pending">{item.status.replaceAll("_"," ")}</span></p><time>{new Date(item.createdAt).toLocaleString()}</time><Link className="mini-btn approve" style={{marginTop:8}} href={`/${locale}/admin/compliance/${item.id}`}>Review evidence</Link></div></div>):<div className="activity"><span className="activity-icon"><BadgeCheck size={16}/></span><div><p><strong>Queue clear</strong><br/>No property compliance cases need review.</p><time>Live database</time></div></div>}</div></div>
    </div><div className="panel" style={{marginTop:20}}><div className="panel-head"><h2>Local environment</h2><span className="muted" style={{fontSize:12}}>All counts above are queried from Supabase with staff RLS.</span></div></div>
  </div></div>;
}
