"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { FileCheck2, Upload } from "lucide-react";
import type { Requirement } from "@/lib/verification";

type DocumentSummary={id:string;requirement_code:string;status:string;original_name:string;review_note:string|null;expires_on:string|null;version:number};
export function EvidenceUploader({scope,scopeId,requirements,documents,editable=true}:{scope:"application"|"compliance";scopeId:string;requirements:Requirement[];documents:DocumentSummary[];editable?:boolean}){const router=useRouter();const [busy,setBusy]=useState<string>();const [message,setMessage]=useState("");async function upload(code:string,event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(code);setMessage("");const form=new FormData(event.currentTarget);form.set("scope",scope);form.set("scopeId",scopeId);form.set("requirementCode",code);const response=await fetch("/api/evidence",{method:"POST",body:form});const data=await response.json();if(!response.ok){setMessage(data.error??"Upload failed");setBusy(undefined);return;}setBusy(undefined);router.refresh();}
return <div><div className="activity-list">{requirements.map(requirement=>{const doc=documents.filter(item=>item.requirement_code===requirement.code&&!['superseded','purged'].includes(item.status)).sort((a,b)=>b.version-a.version)[0];return <div className="activity" key={requirement.code} style={{alignItems:"flex-start"}}><span className="activity-icon"><FileCheck2 size={16}/></span><div style={{width:"100%"}}><p><strong>{requirement.label}</strong> <span className={`status ${doc?.status==="verified"?"live":doc?.status==="rejected"?"declined":"pending"}`}>{doc?.status??"missing"}</span><br/><span className="muted">{requirement.description}</span></p><div style={{fontSize:11,marginBottom:8}}>{requirement.source==="statutory"?"Legal evidence":"FindVillas policy"}{doc?` · ${doc.original_name} · v${doc.version}`:""}{doc?.review_note?` · ${doc.review_note}`:""}</div>{editable&&<form onSubmit={event=>upload(requirement.code,event)}><div className="booking-grid"><div className="booking-field full"><label>PDF or image</label><input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required/></div><div className="booking-field"><label>Document number</label><input name="documentNumber"/></div><div className="booking-field"><label>Issuing authority</label><input name="issuingAuthority"/></div><div className="booking-field"><label>Issued on</label><input name="issuedOn" type="date"/></div><div className="booking-field"><label>Expires on{requirement.expires?" (required)":""}</label><input name="expiresOn" type="date" required={requirement.expires}/></div></div><button className="mini-btn approve" style={{marginTop:8}} disabled={busy===requirement.code}><Upload size={13}/>{busy===requirement.code?"Uploading…":doc?"Replace evidence":"Upload evidence"}</button></form>}</div></div>})}</div>{message&&<div className="notice" style={{marginTop:12}}>{message}</div>}</div>}
