"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ImageUp, Send } from "lucide-react";
import type { Locale } from "@/lib/types";

export function NewVillaForm({locale,destinations}:{locale:Locale;destinations:{id:string;name:string}[]}){const router=useRouter();const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [files,setFiles]=useState<FileList|null>(null);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/partner/villas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),destinationId:form.get("destinationId"),legalPath:form.get("legalPath"),bedrooms:Number(form.get("bedrooms")),bathrooms:Number(form.get("bathrooms")),maxGuests:Number(form.get("maxGuests")),baseRateThb:Number(form.get("baseRateThb")),latitude:Number(form.get("latitude")),longitude:Number(form.get("longitude")),areaEn:form.get("areaEn"),areaTh:form.get("areaTh"),address:{line1:form.get("addressLine"),district:form.get("addressDistrict"),province:form.get("addressProvince"),postalCode:form.get("addressPostalCode")},descriptionEn:form.get("descriptionEn"),descriptionTh:form.get("descriptionTh"),amenities:String(form.get("amenities")??"").split(",").map(value=>value.trim()).filter(Boolean)})});const data=await response.json();if(!response.ok){setError(data.error??"Could not submit listing");setLoading(false);return;}if(files){for(const file of Array.from(files)){const upload=new FormData();upload.set("file",file);await fetch(`/api/partner/villas/${data.id}/media`,{method:"POST",body:upload});}}router.push(`/${locale}/partner/compliance/${data.complianceCaseId}`);router.refresh();}
  return <div className="dashboard-shell"><div className="container" style={{maxWidth:820}}><div className="eyebrow muted">Partner listing</div><h1 className="serif" style={{fontSize:44,fontWeight:400}}>Submit a villa</h1><p className="muted">The listing and its images are stored locally, then enter the staff review queue.</p><form className="panel" style={{padding:28}} onSubmit={submit}><div className="booking-grid">
    <div className="booking-field full"><label>Villa name</label><input name="name" required/></div><div className="booking-field"><label>Destination</label><select name="destinationId" required>{destinations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="booking-field"><label>Legal accommodation path</label><select name="legalPath" required><option value="hotel_license">Hotel business licence</option><option value="non_hotel_notification">DOPA non-hotel notification (max 8 rooms / 30 guests)</option></select></div>
    <div className="booking-field"><label>Bedrooms</label><input name="bedrooms" type="number" min="1" defaultValue="4" required/></div><div className="booking-field"><label>Bathrooms</label><input name="bathrooms" type="number" min="1" defaultValue="4" required/></div><div className="booking-field"><label>Maximum guests</label><input name="maxGuests" type="number" min="1" defaultValue="8" required/></div><div className="booking-field"><label>Base rate (THB)</label><input name="baseRateThb" type="number" min="1" defaultValue="25000" required/></div>
    <div className="booking-field"><label>Latitude</label><input name="latitude" type="number" step="any" defaultValue="7.95" required/></div><div className="booking-field"><label>Longitude</label><input name="longitude" type="number" step="any" defaultValue="98.3" required/></div>
    <div className="booking-field"><label>Area (English)</label><input name="areaEn" required/></div><div className="booking-field"><label>Area (Thai)</label><input name="areaTh" required/></div><div className="booking-field full"><label>Exact legal address</label><input name="addressLine" required/></div><div className="booking-field"><label>District</label><input name="addressDistrict" required/></div><div className="booking-field"><label>Province</label><input name="addressProvince" required/></div><div className="booking-field"><label>Postal code</label><input name="addressPostalCode" required/></div><div className="booking-field full"><label>Description (English)</label><input name="descriptionEn" required/></div><div className="booking-field full"><label>Description (Thai)</label><input name="descriptionTh" required/></div><div className="booking-field full"><label>Amenities (comma-separated)</label><input name="amenities" placeholder="Pool, Private chef, Ocean view" required/></div><div className="booking-field full"><label><ImageUp size={15}/> Villa images</label><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={event=>setFiles(event.target.files)}/></div>
  </div>{error&&<div className="notice" style={{marginTop:16}}>{error}</div>}<button className="btn btn-primary" style={{marginTop:20}} disabled={loading}><Send size={17}/>{loading?"Submitting…":"Submit for review"}</button></form></div></div>;
}
