"use client";

import { useState } from "react";
import { Bell, CalendarDays, CheckCircle2, Clock3, Plus, UserRoundCheck } from "lucide-react";
import Link from "next/link";
import type { Locale } from "@/lib/types";

export type PartnerRequestRow = {id:string;reference:string;guest:string;villa:string;dates:string;guests:number;total:string;status:string};
export type PartnerComplianceRow = {id:string;villa:string;legalPath:string;status:string;updatedAt:string};

export function PartnerDashboard({ locale, initialRequests, complianceCases, villaCount, partnerName }: { locale: Locale; initialRequests:PartnerRequestRow[]; complianceCases:PartnerComplianceRow[]; villaCount:number; partnerName:string }) {
  const [requests,setRequests]=useState(initialRequests); const [toast,setToast]=useState("");
  async function act(id:string,status:"approved"|"declined"){const response=await fetch(`/api/partner/booking-requests/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:status==="approved"?"approve":"decline"})});const data=await response.json();if(!response.ok){setToast(data.error??"Action failed");return;}setRequests(rows=>rows.map(row=>row.id===id?{...row,status:data.status}:row));setToast(status==="approved"?"Dates held for 24 hours and guest notified.":"Request declined and guest notified.");setTimeout(()=>setToast(""),3200);}
  return <div className="dashboard-shell"><div className="container"><div className="dash-head"><div><div className="eyebrow muted">Partner portal · {partnerName}</div><h1 className="serif">{locale==="th"?"แดชบอร์ดพาร์ทเนอร์":"Partner dashboard"}</h1></div><Link className="btn btn-primary" href={`/${locale}/partner/villas/new`}><Plus size={17}/> Add a villa</Link></div>
    <div className="notice"><strong>Account verified.</strong> Your published villas are visible to guests. New listings and material edits go to staff review.</div>
    <div className="stat-grid"><div className="stat-card"><div className="stat-label">Awaiting response</div><div className="stat-value">{requests.filter(r=>r.status==="submitted").length}</div></div><div className="stat-card"><div className="stat-label">Active holds</div><div className="stat-value">{requests.filter(r=>r.status==="approved_payment_pending").length}</div></div><div className="stat-card"><div className="stat-label">Published villas</div><div className="stat-value">{villaCount}</div></div><div className="stat-card"><div className="stat-label">Response rate</div><div className="stat-value">—</div></div></div>
    <div className="dash-grid"><div className="panel"><div className="panel-head"><h2>Booking requests</h2><span className="status pending"><Clock3 size={12}/> Reply in 24h</span></div><div className="table-wrap"><table><thead><tr><th>Guest</th><th>Villa & dates</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{r.guest}</strong><br/><span className="muted">{r.guests} guests</span></td><td><strong>{r.villa}</strong><br/><span className="muted">{r.dates}</span></td><td>{r.total}</td><td><span className={`status ${r.status==="submitted"?"pending":"live"}`}>{r.status}</span></td><td><div className="action-row">{r.status==="submitted"&&<><button className="mini-btn approve" onClick={()=>act(r.id,"approved")}>Approve</button><button className="mini-btn" onClick={()=>act(r.id,"declined")}>Decline</button></>}<Link className="mini-btn" href={`/${locale}/partner/requests/${r.id}`}>View</Link></div></td></tr>)}</tbody></table></div></div>
      <div className="panel"><div className="panel-head"><h2>Today</h2><Bell size={17}/></div><div className="activity-list"><div className="activity"><span className="activity-icon"><CalendarDays size={16}/></span><div><p><strong>Database connected</strong><br/>Availability and requests are read from local Supabase.</p><time>Live</time></div></div><div className="activity"><span className="activity-icon"><UserRoundCheck size={16}/></span><div><p><strong>{requests.length} requests</strong><br/>Only requests for your organization are visible.</p><time>RLS protected</time></div></div><div className="activity"><span className="activity-icon"><CheckCircle2 size={16}/></span><div><p><strong>Account verified</strong><br/>Listing edits require staff review.</p><time>Active</time></div></div></div></div>
    </div><div className="panel" style={{marginTop:20}}><div className="panel-head"><h2>Villa verification</h2><span className="muted" style={{fontSize:12}}>A separate compliance gate applies to every villa</span></div><div className="table-wrap"><table><thead><tr><th>Villa</th><th>Legal path</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>{complianceCases.length?complianceCases.map(item=><tr key={item.id}><td><strong>{item.villa}</strong></td><td>{item.legalPath.replaceAll("_"," ")}</td><td><span className={`status ${item.status==="approved"?"live":item.status==="rejected"||item.status==="suspended"?"declined":"pending"}`}>{item.status.replaceAll("_"," ")}</span></td><td>{new Date(item.updatedAt).toLocaleDateString()}</td><td><Link className="mini-btn" href={`/${locale}/partner/compliance/${item.id}`}>{["draft","changes_requested"].includes(item.status)?"Continue":"View"}</Link></td></tr>):<tr><td colSpan={5} className="muted">No villas have entered verification yet.</td></tr>}</tbody></table></div></div>{toast&&<div className="toast">{toast}</div>}
  </div></div>;
}
