"use client";

import { useState } from "react";
import Script from "next/script";
import Link from "next/link";
import Image from "next/image";
import { CheckCircle2, CreditCard, LockKeyhole, QrCode } from "lucide-react";
import type { Locale } from "@/lib/types";

declare global { interface Window { Omise?: { setPublicKey:(key:string)=>void; createToken:(type:"card",data:Record<string,string>,callback:(status:number,response:{id?:string;message?:string})=>void)=>void } } }
export type CheckoutRequest={id:string;villaName:string;checkIn:string;checkOut:string;total:number;status:string};

export function PaymentCheckout({ bookingRequest, locale, publicKey }: { bookingRequest:CheckoutRequest; locale:Locale; publicKey:string }) {
  const [method,setMethod]=useState<"card"|"promptpay">("promptpay");const [done,setDone]=useState(bookingRequest.status==="confirmed");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [qrUrl,setQrUrl]=useState<string>();
  const [card,setCard]=useState({name:"Test User",number:"4242424242424242",expiration_month:"12",expiration_year:"2030",security_code:"123"});
  async function pay(cardToken?:string){const response=await fetch("/api/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:bookingRequest.id,method,cardToken,idempotencyKey:crypto.randomUUID()})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Payment failed");if(data.status==="successful")setDone(true);else if(data.authorizeUri)window.location.assign(data.authorizeUri);else if(data.qrUrl)setQrUrl(data.qrUrl);else setError(`Payment is ${data.status}. Omise will update it by webhook.`);}
  async function complete(){setLoading(true);setError("");try{if(method==="promptpay"){await pay();return;}if(!window.Omise)throw new Error("Omise.js is still loading");window.Omise.setPublicKey(publicKey);await new Promise<void>((resolve,reject)=>window.Omise!.createToken("card",card,(status,response)=>{if(status!==200||!response.id){reject(new Error(response.message??"Card tokenization failed"));return;}pay(response.id).then(resolve,reject);}));}catch(cause){setError(cause instanceof Error?cause.message:"Payment failed");}finally{setLoading(false);}}
  if(done)return <div className="container" style={{maxWidth:650,padding:"80px 0",textAlign:"center"}}><CheckCircle2 size={62} color="#b9684f"/><h1 className="section-title serif" style={{marginTop:22}}>Booking confirmed</h1><p className="muted" style={{lineHeight:1.7}}>The Omise test charge succeeded and a test-mode booking was saved in Supabase. No real funds moved.</p><Link className="btn btn-dark" href={`/${locale}/trips`}>View my trips</Link></div>;
  return <div className="dashboard-shell"><Script src="https://cdn.omise.co/omise.js" strategy="afterInteractive"/><div className="container" style={{maxWidth:720}}><div className="eyebrow muted">Omise test checkout</div><h1 className="serif" style={{fontSize:44,fontWeight:400}}>Complete test payment</h1><div className="notice"><strong>Test mode.</strong> Omise processes this against test credentials; no real funds move.</div>
    <div className="panel" style={{padding:24}}><div style={{display:"flex",justifyContent:"space-between",gap:20,borderBottom:"1px solid var(--line)",paddingBottom:20,marginBottom:20}}><div><strong>{bookingRequest.villaName}</strong><div className="muted" style={{fontSize:13,marginTop:6}}>{bookingRequest.checkIn} → {bookingRequest.checkOut}</div></div><strong>฿{bookingRequest.total.toLocaleString()}</strong></div>
    <h3>Choose a test method</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:20}}><button className={`filter-chip ${method==="promptpay"?"active":""}`} onClick={()=>setMethod("promptpay")}><QrCode size={16}/> PromptPay</button><button className={`filter-chip ${method==="card"?"active":""}`} onClick={()=>setMethod("card")}><CreditCard size={16}/> Card</button></div>
    {method==="card"?<div className="booking-grid" style={{marginBottom:20}}><div className="booking-field full"><label>Name on card</label><input value={card.name} onChange={e=>setCard({...card,name:e.target.value})}/></div><div className="booking-field full"><label>Test card</label><input value={card.number} onChange={e=>setCard({...card,number:e.target.value.replace(/\s/g,"")})}/></div><div className="booking-field"><label>Expiry month / year</label><input value={`${card.expiration_month}/${card.expiration_year}`} onChange={e=>{const [month,year]=e.target.value.split("/");setCard({...card,expiration_month:month??"",expiration_year:year??""});}}/></div><div className="booking-field"><label>CVC</label><input value={card.security_code} onChange={e=>setCard({...card,security_code:e.target.value})}/></div></div>:<div style={{background:"var(--cream)",padding:25,textAlign:"center",borderRadius:15,marginBottom:20}}>{qrUrl?<Image src={qrUrl} alt="PromptPay QR" width={220} height={220} unoptimized/>:<><QrCode size={110}/><p className="muted">Create a real Omise test QR</p></>}</div>}
    {error&&<div className="notice" style={{marginBottom:16}}>{error}</div>}<button className="btn btn-primary" style={{width:"100%"}} onClick={complete} disabled={loading||!!qrUrl}><LockKeyhole size={17}/>{loading?"Processing…":method==="card"?"Pay with test card":"Create PromptPay QR"}</button><p className="fine-print">{method==="promptpay"?"Scan the QR with a supported Thai banking app. No card details are required.":"Card details go directly to Omise.js and never touch the FindVillas server."}</p></div>
  </div></div>;
}
